// DO NOT EDIT. This file is generated by remix-deno-jit.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `deno task dev`.

import * as serverEntry from "./app/entry.server.tsx";
import * as route0 from "./app/root.tsx";
import * as route1 from "./app/routes/update.tsx";
import * as route2 from "./app/routes/index.tsx";

export const entry = { module: serverEntry };
export const routes = {
	"root": {
		id: "root",
		module: route0,
		file: "./app/root.tsx",
	},
	"routes/update": {
		id: "routes/update",
		path: "update",
		parentId: "root",
		module: route1,
		file: "./app/routes/update.tsx",
	},
	"routes/index": {
		id: "routes/index",
		index: true,
		parentId: "root",
		module: route2,
		file: "./app/routes/index.tsx",
	},
};
export const assets = {
  entry: { imports: [], module: "/entry.client.js" },
  routes: {
		"root": {
			id: "root",
			imports: [],
			module: "/root.js",
			hasAction: "action" in route0,
			hasLoader: "loader" in route0,
			hasCatchBoundary: "CatchBoundary" in route0,
			hasErrorBoundary: "ErrorBoundary" in route0,
		},
			"routes/update": {
			id: "routes/update",
			path: "update",
			parentId: "root",
			imports: [],
			module: "/routes/update.js",
			hasAction: "action" in route1,
			hasLoader: "loader" in route1,
			hasCatchBoundary: "CatchBoundary" in route1,
			hasErrorBoundary: "ErrorBoundary" in route1,
		},
			"routes/index": {
			id: "routes/index",
			index: true,
			parentId: "root",
			imports: [],
			module: "/routes/index.js",
			hasAction: "action" in route2,
			hasLoader: "loader" in route2,
			hasCatchBoundary: "CatchBoundary" in route2,
			hasErrorBoundary: "ErrorBoundary" in route2,
		},		
},
};
export const future = { v2_errorBoundary: true };
