#!/bin/bash
set -ex

_scripts="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_project="${_scripts}/.."

export $(grep -v '^#' $_project/.env | xargs)

# echo $_scripts
# echo $_project

pushd $_project

# use podman
podman build -f ./Dockerfile . -t $APP_NAME:latest

popd

