#!/bin/bash
set -ex

_scripts="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_project="${_scripts}/.."

export $(grep -v '^#' $_project/.env | xargs)

# echo $DOCKER_REGISTRY_HOST

podman image tag $APP_NAME $DOCKER_REGISTRY_HOST/$APP_NAME
podman push $DOCKER_REGISTRY_HOST/$APP_NAME:latest

kubectl -n snow-tracker rollout restart deploy snow-tracker-service