name = "api"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-12-24"
kv_namespaces = [
  { binding = "snow", preview_id = "7734dc146be6407eb39f60a6d1754372", id = "482d35638d3d4624aee49dc1117023cb" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[triggers]
crons = [
  # At minute 2 past every hour from 12 through 20.
  "*/2 12-20 * * *",

  # At every 5th minute past every hour from 0 through 12 and every hour from 20 through 23.
  "*/5 0-12,20-23 * * *"
]