name = "api"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-12-24"
kv_namespaces = [
  { binding = "snow", preview_id = "7734dc146be6407eb39f60a6d1754372", id = "482d35638d3d4624aee49dc1117023cb" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[triggers]
crons = [
  "*/5 * * * *"
]