name: Deploy Server

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          PROJECT_NAME: 'snow'
          TERRAFORM_STATE_BUCKET: 'tyrsius-terraform-state'
          TERRAFORM_KEY: 'snow'
          APP_NAMESPACE: 'snow'
          SITE_DOMAIN: 'snow.kye.dev'
      - name: Deploy
        run: make client
