name: Deploy Server

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
      - 'infrastructure/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Make envfile
        uses: kyeotic/create-envfile
        with:
          envkey_PROJECT_NAME: 'snow'
          envkey_TERRAFORM_STATE_BUCKET: 'tyrsius-terraform-state'
          envkey_TERRAFORM_KEY: 'snow'
          envkey_APP_NAMESPACE: 'snow'
          envkey_SITE_DOMAIN: 'snow.kye.dev'
      - name: Install Terraform
        env:
          TERRAFORM_VERSION: '0.12.18'
        run: |
          tf_version=$TERRAFORM_VERSION
          wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
          unzip terraform_"$tf_version"_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
      - name: Deploy
        run: export CI=true && make server
